### ISSUE TITLE
YAML output option?

### ISSUE THREAD

**Issue by julesjacobsen** [TheJacksonLaboratory/PhenopacketGenerator#17]
Could we have an option to output yaml as well as json? It reads better for configuration files and I'd like to use this for Exomiser input which uses yaml config.

It's trivial to convert JSON to YAML:

```java
String yaml = new YAMLMapper().writeValueAsString(jsonNode);
```

```yaml
---
family:
  proband:
    subject:
      id: "manuel"
    phenotypicFeatures:
    - type:
        id: "HP:0001156"
        label: "Brachydactyly"
    - type:
        id: "HP:0001363"
        label: "Craniosynostosis"
    - type:
        id: "HP:0011304"
        label: "Broad thumb"
    - type:
        id: "HP:0010055"
        label: "Broad hallux"
    htsFiles:
    - uri: "file://Pfeiffer.vcf"
      htsFormat: "VCF"
      genomeAssembly: "GRCh37"
  pedigree:
    persons:
    - individualId: "manuel"
      sex: "MALE"
      affectedStatus: "AFFECTED"
```

compared to 
```json
{
  "family": {
    "proband": {
      "subject": {
        "id": "manuel"
      },
      "phenotypicFeatures": [{
        "type": {
          "id": "HP:0001156",
          "label": "Brachydactyly"
        }
      }, {
        "type": {
          "id": "HP:0001363",
          "label": "Craniosynostosis"
        }
      }, {
        "type": {
          "id": "HP:0011304",
          "label": "Broad thumb"
        }
      }, {
        "type": {
          "id": "HP:0010055",
          "label": "Broad hallux"
        }
      }],
      "htsFiles": [{
        "uri": "file://Pfeiffer.vcf",
        "htsFormat": "VCF",
        "genomeAssembly": "GRCh37"
      }]
    },
    "pedigree": {
      "persons": [{
        "individualId": "manuel",
        "sex": "MALE",
        "affectedStatus": "AFFECTED"
      }]
    }
  }
}
```
